-- 코드를 작성해주세요
WITH A AS(SELECT ID
FROM ECOLI_DATA
WHERE PARENT_ID IS NULL)
, B AS (SELECT B.ID
       FROM A JOIN ECOLI_DATA B ON A.ID=B.PARENT_ID)

SELECT C.ID
FROM B JOIN ECOLI_DATA C ON B.ID=C.PARENT_ID
ORDER BY ID