# -- 코드를 작성해주세요
# WITH A AS(SELECT ID
# FROM ECOLI_DATA
# WHERE PARENT_ID IS NULL)
# , B AS (SELECT B.ID
#        FROM A JOIN ECOLI_DATA B ON A.ID=B.PARENT_ID)

# SELECT C.ID
# FROM B JOIN ECOLI_DATA C ON B.ID=C.PARENT_ID
# ORDER BY ID


WITH FIR AS (
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL),
SECOND AS(
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IN (SELECT ID FROM FIR)),
THIRD AS (
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IN (SELECT ID FROM SECOND))
SELECT ID
FROM THIRD
ORDER BY ID