SELECT d.ID
FROM
(SELECT b.ID
FROM ECOLI_DATA a
JOIN ECOLI_DATA b
ON a.ID = b.PARENT_ID) c
JOIN ECOLI_DATA d
ON c.ID = d.PARENT_ID
WHERE d.ID NOT IN (SELECT f.ID
FROM (SELECT d.ID
FROM
(SELECT b.ID
FROM ECOLI_DATA a
JOIN ECOLI_DATA b
ON a.ID = b.PARENT_ID) c
JOIN ECOLI_DATA d
ON c.ID = d.PARENT_ID) e
JOIN ECOLI_DATA f
ON e.ID = f.PARENT_ID)
ORDER BY ID