-- 코드를 작성해주세요
WITH ID AS (SELECT ITEM_ID
FROM ITEM_INFO
WHERE ITEM_ID NOT IN (SELECT DISTINCT COALESCE(PARENT_ITEM_ID,99999999) FROM ITEM_TREE))

SELECT ITEM_ID,ITEM_NAME,RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (SELECT ITEM_ID FROM ID)
ORDER BY ITEM_ID DESC


# -- 트리 테이블 부모 ID에 ITEM_INFO의 ID가 없어야 함. 

#SELECT DISTINCT COALESCE(PARENT_ITEM_ID,99999999) FROM ITEM_TREE