SELECT ID, CHILD_COUNT
FROM (SELECT a.ID, COUNT(*) AS "CHILD_COUNT"
FROM ECOLI_DATA a
JOIN ECOLI_DATA b
ON a.ID = b.PARENT_ID
GROUP BY a.ID) c
UNION
(SELECT ID, 0 AS "CHILD_COUNT"
FROM ECOLI_DATA
WHERE ID NOT IN (SELECT a.ID
FROM ECOLI_DATA a
JOIN ECOLI_DATA b
ON a.ID = b.PARENT_ID
GROUP BY a.ID))
ORDER BY ID