-- 코드를 입력하세요
-- SELECT a.ANIMAL_ID, a.NAME
-- FROM ANIMAL_INS a
-- WHERE a.ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS)
-- ORDER BY a.ANIMAL_ID

SELECT a.ANIMAL_ID, a.NAME
FROM ANIMAL_OUTS a
WHERE a.ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_INS)
ORDER BY a.ANIMAL_ID