-- 코드를 입력하세요
WITH TOTAL AS (
SELECT USER_ID
FROM USER_INFO
WHERE YEAR(JOINED) = 2021)

SELECT YEAR(sales_date) AS YEAR, MONTH(sales_date) AS MONTH, COUNT(DISTINCT(user_id)) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT(user_id))/(SELECT COUNT(*) FROM TOTAL),1) AS PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (SELECT USER_ID FROM TOTAL)
GROUP BY YEAR(sales_date), MONTH(sales_date)
ORDER BY YEAR, MONTH