-- 코드를 작성해주세요
WITH FRONT AS(
    SELECT CODE
    FROM SKILLCODES
    WHERE CATEGORY LIKE "Front End"
)
SELECT DISTINCT d.ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS d JOIN FRONT f ON (d.SKILL_CODE & f.CODE)
ORDER BY ID