-- 코드를 입력하세요

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS "REVIEW_DATE"
FROM MEMBER_PROFILE m JOIN REST_REVIEW r ON m.MEMBER_ID=r.MEMBER_ID
WHERE m.MEMBER_ID IN
    (SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) IN 
        (SELECT MAX(CNT) AS CNT
        FROM (SELECT COUNT(*) AS CNT
            FROM REST_REVIEW
            GROUP BY MEMBER_ID) a))
ORDER BY REVIEW_DATE, REVIEW_TEXT