-- 코드를 입력하세요
WITH A AS (SELECT COUNT(*) AS CNT
FROM REST_REVIEW 
GROUP BY MEMBER_ID
ORDER BY CNT DESC LIMIT 1),
B AS (SELECT MEMBER_ID
     FROM REST_REVIEW 
     GROUP BY MEMBER_ID
     HAVING COUNT(*) = (SELECT CNT FROM A)),
C AS (SELECT MEMBER_ID,REVIEW_TEXT,REVIEW_DATE
     FROM REST_REVIEW
     WHERE MEMBER_ID IN (SELECT MEMBER_ID FROM B))
     
SELECT MEMBER_NAME, REVIEW_TEXT,DATE_FORMAT(REVIEW_DATE,"%Y-%m-%d") AS "REVIEW_DATE"
FROM C JOIN MEMBER_PROFILE M ON C.MEMBER_ID=M.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT