-- 코드를 작성해주세요
SELECT a.ITEM_ID,ITEM_NAME, RARITY
FROM 
(SELECT *
FROM ITEM_TREE
WHERE PARENT_ITEM_ID IN
(SELECT ITEM_ID
FROM ITEM_INFO
WHERE RARITY LIKE "RARE")
) a JOIN ITEM_INFO b ON a.ITEM_ID = b.ITEM_ID
ORDER BY a.ITEM_ID DESC

-- RARE템 정보만 뽑기.
-- 해당 아이템을 부모로 갖는 값들 찾기 -> ID 뽑기