-- 코드를 작성해주세요
WITH RARE AS (
SELECT ITEM_ID
FROM ITEM_INFO
WHERE RARITY LIKE "RARE"), 
TWO AS (SELECT t.ITEM_ID
FROM ITEM_TREE t JOIN RARE r ON t.PARENT_ITEM_ID=r.ITEM_ID)

SELECT ITEM_ID,ITEM_NAME,RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (SELECT ITEM_ID FROM TWO)
ORDER BY ITEM_ID DESC