-- 코드를 작성해주세요
SELECT a.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO a
JOIN ITEM_TREE b ON a.ITEM_ID = b.ITEM_ID
WHERE b.PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = "RARE")
ORDER BY ITEM_ID DESC;