-- 코드를 입력하세요
# SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY YEAR(START_DATE), MONTH(START_DATE), CAR_ID
# HAVING (COUNT(*) >= 5) AND (YEAR(START_DATE) = 2022) AND (MONTH(START_DATE) BETWEEN 8 AND 10)
# ORDER BY MONTH, CAR_ID DESC

# 대여 시작일 기준 22년 8월-10월 추리기 
# GROUP BY 차
# HAVING COUNT(*) >= 5

WITH ID AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE (YEAR(START_DATE) = 2022) AND (MONTH(START_DATE) BETWEEN 8 AND 10)
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5)

SELECT MONTH(START_DATE) AS MONTH,CAR_ID,COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE (CAR_ID IN (SELECT CAR_ID FROM ID)) AND (YEAR(START_DATE) = 2022) AND (MONTH(START_DATE) BETWEEN 8 AND 10)
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH, CAR_ID DESC
# 월별로 자동차 총 대여 갯수 출력하기