-- 코드를 입력하세요
SELECT a.BOOK_ID, b.AUTHOR_NAME, DATE_FORMAT(A.PUBLISHED_DATE, "%Y-%m-%d") AS "PUBLISHED_DATE"
FROM BOOK a
JOIN AUTHOR b 
ON a.AUTHOR_ID = b.AUTHOR_ID
WHERE a.CATEGORY LIKE "경제" 
ORDER BY A.PUBLISHED_DATE 